"""Link policies to virtual accounts

Revision ID: 3c4d5e6f7g8h
Revises: 2a3b4c5d6e7f
Create Date: 2024-12-19 15:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '3c4d5e6f7g8h'
down_revision = '2a3b4c5d6e7f'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if virtual_accounts table exists, if not create it first
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    
    if 'virtual_accounts' not in inspector.get_table_names():
        # Create virtual_accounts table first
        op.create_table('virtual_accounts',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('user_id', sa.Integer(), nullable=False),
            sa.Column('customer_identifier', sa.String(100), nullable=False),
            sa.Column('virtual_account_number', sa.String(20), nullable=False),
            sa.Column('bank_code', sa.String(10), nullable=False),
            sa.Column('account_type', sa.String(20), nullable=False),
            sa.Column('business_name', sa.String(100), nullable=True),
            sa.Column('email', sa.String(100), nullable=True),
            sa.Column('mobile_number', sa.String(20), nullable=True),
            sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
            sa.Column('squad_created_at', sa.DateTime(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')),
            sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index('ix_virtual_accounts_user_id', 'virtual_accounts', ['user_id'])
        op.create_index('ix_virtual_accounts_customer_identifier', 'virtual_accounts', ['customer_identifier'])
        op.create_index('ix_virtual_accounts_virtual_account_number', 'virtual_accounts', ['virtual_account_number'])
        op.create_foreign_key('fk_virtual_accounts_user_id', 'virtual_accounts', 'users', ['user_id'], ['id'])
    
    if 'virtual_account_transactions' not in inspector.get_table_names():
        # Create virtual_account_transactions table
        op.create_table('virtual_account_transactions',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('virtual_account_id', sa.Integer(), nullable=False),
            sa.Column('transaction_reference', sa.String(100), nullable=False),
            sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
            sa.Column('currency', sa.String(3), nullable=False, server_default='NGN'),
            sa.Column('transaction_type', sa.String(50), nullable=False),
            sa.Column('transaction_date', sa.DateTime(), nullable=False),
            sa.Column('description', sa.Text(), nullable=True),
            sa.Column('sender_name', sa.String(255), nullable=True),
            sa.Column('sender_account', sa.String(20), nullable=True),
            sa.Column('sender_bank', sa.String(100), nullable=True),
            sa.Column('status', sa.String(20), nullable=False, server_default='pending'),
            sa.Column('squad_transaction_id', sa.String(100), nullable=True),
            sa.Column('webhook_data', sa.Text(), nullable=True),
            sa.Column('processed_at', sa.DateTime(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')),
            sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index('ix_virtual_account_transactions_virtual_account_id', 'virtual_account_transactions', ['virtual_account_id'])
        op.create_index('ix_virtual_account_transactions_transaction_reference', 'virtual_account_transactions', ['transaction_reference'])
        op.create_index('ix_virtual_account_transactions_status', 'virtual_account_transactions', ['status'])
        op.create_foreign_key('fk_virtual_account_transactions_virtual_account_id', 'virtual_account_transactions', 'virtual_accounts', ['virtual_account_id'], ['id'])
    
    # Now add policy_id column to virtual_accounts
    op.add_column('virtual_accounts', sa.Column('policy_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_virtual_accounts_policy_id', 'virtual_accounts', 'policies', ['policy_id'], ['id'])
    op.create_index('ix_virtual_accounts_policy_id', 'virtual_accounts', ['policy_id'])
    
    # Add settlement tracking columns to virtual_account_transactions
    op.add_column('virtual_account_transactions', sa.Column('settlement_status', sa.String(20), nullable=False, server_default='pending'))
    op.add_column('virtual_account_transactions', sa.Column('settlement_date', sa.DateTime(), nullable=True))
    op.add_column('virtual_account_transactions', sa.Column('settlement_reference', sa.String(100), nullable=True))
    op.add_column('virtual_account_transactions', sa.Column('gaps_transaction_ref', sa.String(100), nullable=True))
    
    # Create index for settlement queries
    op.create_index('ix_virtual_account_transactions_settlement_status', 'virtual_account_transactions', ['settlement_status'])
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove settlement tracking columns
    op.drop_index('ix_virtual_account_transactions_settlement_status', 'virtual_account_transactions')
    op.drop_column('virtual_account_transactions', 'gaps_transaction_ref')
    op.drop_column('virtual_account_transactions', 'settlement_reference')
    op.drop_column('virtual_account_transactions', 'settlement_date')
    op.drop_column('virtual_account_transactions', 'settlement_status')
    
    # Remove policy relationship
    op.drop_index('ix_virtual_accounts_policy_id', 'virtual_accounts')
    op.drop_constraint('fk_virtual_accounts_policy_id', 'virtual_accounts', type_='foreignkey')
    op.drop_column('virtual_accounts', 'policy_id')
    # ### end Alembic commands ###
