"""Link policies to virtual accounts

Revision ID: 3c4d5e6f7g8h
Revises: 2a3b4c5d6e7f
Create Date: 2024-12-19 15:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '3c4d5e6f7g8h'
down_revision = '2a3b4c5d6e7f'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add policy_id column to virtual_accounts table
    op.add_column('virtual_accounts', sa.Column('policy_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_virtual_accounts_policy_id', 'virtual_accounts', 'policies', ['policy_id'], ['id'])
    op.create_index('ix_virtual_accounts_policy_id', 'virtual_accounts', ['policy_id'])
    
    # Add settlement tracking columns to virtual_account_transactions
    op.add_column('virtual_account_transactions', sa.Column('settlement_status', sa.String(20), nullable=False, server_default='pending'))
    op.add_column('virtual_account_transactions', sa.Column('settlement_date', sa.DateTime(), nullable=True))
    op.add_column('virtual_account_transactions', sa.Column('settlement_reference', sa.String(100), nullable=True))
    op.add_column('virtual_account_transactions', sa.Column('gaps_transaction_ref', sa.String(100), nullable=True))
    
    # Create index for settlement queries
    op.create_index('ix_virtual_account_transactions_settlement_status', 'virtual_account_transactions', ['settlement_status'])
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove settlement tracking columns
    op.drop_index('ix_virtual_account_transactions_settlement_status', 'virtual_account_transactions')
    op.drop_column('virtual_account_transactions', 'gaps_transaction_ref')
    op.drop_column('virtual_account_transactions', 'settlement_reference')
    op.drop_column('virtual_account_transactions', 'settlement_date')
    op.drop_column('virtual_account_transactions', 'settlement_status')
    
    # Remove policy relationship
    op.drop_index('ix_virtual_accounts_policy_id', 'virtual_accounts')
    op.drop_constraint('fk_virtual_accounts_policy_id', 'virtual_accounts', type_='foreignkey')
    op.drop_column('virtual_accounts', 'policy_id')
    # ### end Alembic commands ###
