"""Initial migration

Revision ID: 7a6867361e2b
Revises: 
Create Date: 2025-06-17 07:30:25.745374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a6867361e2b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insurance_companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('registration_number', sa.String(length=100), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insurance_companies_id'), 'insurance_companies', ['id'], unique=False)
    op.create_index(op.f('ix_insurance_companies_name'), 'insurance_companies', ['name'], unique=True)
    op.create_index(op.f('ix_insurance_companies_registration_number'), 'insurance_companies', ['registration_number'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'BROKER', 'CUSTOMER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('brokers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('license_number', sa.String(length=100), nullable=False),
    sa.Column('agency_name', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('office_address', sa.Text(), nullable=True),
    sa.Column('specialization', sa.String(length=255), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('territory', sa.String(length=255), nullable=True),
    sa.Column('default_commission_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('commission_type', sa.String(length=50), nullable=False),
    sa.Column('total_policies_sold', sa.Integer(), nullable=False),
    sa.Column('total_premiums_collected', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_commission_earned', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verification_date', sa.DateTime(), nullable=True),
    sa.Column('license_expiry_date', sa.DateTime(), nullable=True),
    sa.Column('certifications', sa.Text(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('social_media', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_activity', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['insurance_companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_brokers_company_id'), 'brokers', ['company_id'], unique=False)
    op.create_index(op.f('ix_brokers_id'), 'brokers', ['id'], unique=False)
    op.create_index(op.f('ix_brokers_license_number'), 'brokers', ['license_number'], unique=True)
    op.create_index(op.f('ix_brokers_name'), 'brokers', ['name'], unique=False)
    op.create_table('policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_number', sa.String(length=100), nullable=False),
    sa.Column('policy_type', sa.Enum('LIFE', 'HEALTH', 'AUTO', 'HOME', 'BUSINESS', 'TRAVEL', name='policytype'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('broker_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'EXPIRED', 'CANCELLED', 'PENDING', name='policystatus'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('coverage_details', sa.Text(), nullable=True),
    sa.Column('coverage_amount', sa.String(length=20), nullable=True),
    sa.Column('terms_and_conditions', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['broker_id'], ['brokers.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['insurance_companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policies_broker_id'), 'policies', ['broker_id'], unique=False)
    op.create_index(op.f('ix_policies_company_id'), 'policies', ['company_id'], unique=False)
    op.create_index(op.f('ix_policies_id'), 'policies', ['id'], unique=False)
    op.create_index(op.f('ix_policies_policy_number'), 'policies', ['policy_number'], unique=True)
    op.create_index(op.f('ix_policies_user_id'), 'policies', ['user_id'], unique=False)
    op.create_table('premiums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('billing_cycle', sa.Enum('MONTHLY', 'QUARTERLY', 'SEMI_ANNUAL', 'ANNUAL', name='billingcycle'), nullable=False),
    sa.Column('payment_status', sa.Enum('PENDING', 'PAID', 'OVERDUE', 'CANCELLED', 'REFUNDED', name='paymentstatus'), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('grace_period_days', sa.Integer(), nullable=False),
    sa.Column('late_fee_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('premium_reference', sa.String(length=100), nullable=True),
    sa.Column('payment_reference', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_premiums_due_date'), 'premiums', ['due_date'], unique=False)
    op.create_index(op.f('ix_premiums_id'), 'premiums', ['id'], unique=False)
    op.create_index(op.f('ix_premiums_payment_status'), 'premiums', ['payment_status'], unique=False)
    op.create_index(op.f('ix_premiums_policy_id'), 'premiums', ['policy_id'], unique=False)
    op.create_index(op.f('ix_premiums_premium_reference'), 'premiums', ['premium_reference'], unique=True)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('premium_id', sa.Integer(), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payment_method', sa.Enum('CARD', 'BANK_TRANSFER', 'USSD', 'WALLET', 'CASH', name='paymentmethod'), nullable=False),
    sa.Column('payment_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'SUCCESS', 'FAILED', 'CANCELLED', 'REFUNDED', name='paymenttransactionstatus'), nullable=False),
    sa.Column('transaction_reference', sa.String(length=255), nullable=False),
    sa.Column('external_reference', sa.String(length=255), nullable=True),
    sa.Column('gateway_response', sa.Text(), nullable=True),
    sa.Column('squad_transaction_id', sa.String(length=100), nullable=True),
    sa.Column('squad_payment_ref', sa.String(length=100), nullable=True),
    sa.Column('payer_name', sa.String(length=255), nullable=True),
    sa.Column('payer_email', sa.String(length=255), nullable=True),
    sa.Column('payer_phone', sa.String(length=50), nullable=True),
    sa.Column('processing_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('net_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['premium_id'], ['premiums.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_payment_date'), 'payments', ['payment_date'], unique=False)
    op.create_index(op.f('ix_payments_premium_id'), 'payments', ['premium_id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_payments_transaction_reference'), 'payments', ['transaction_reference'], unique=True)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.Enum('PREMIUM_PAYMENT', 'CLAIM_PAYOUT', 'COMMISSION_PAYMENT', 'REFUND', 'FEE', 'ADJUSTMENT', name='transactiontype'), nullable=False),
    sa.Column('transaction_reference', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', 'REVERSED', name='transactionstatus'), nullable=False),
    sa.Column('related_user_id', sa.Integer(), nullable=True),
    sa.Column('related_policy_id', sa.Integer(), nullable=True),
    sa.Column('related_premium_id', sa.Integer(), nullable=True),
    sa.Column('related_payment_id', sa.Integer(), nullable=True),
    sa.Column('related_broker_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('external_reference', sa.String(length=255), nullable=True),
    sa.Column('batch_reference', sa.String(length=255), nullable=True),
    sa.Column('processed_by', sa.String(length=255), nullable=True),
    sa.Column('processing_method', sa.String(length=100), nullable=True),
    sa.Column('is_reconciled', sa.Boolean(), nullable=False),
    sa.Column('reconciled_date', sa.DateTime(), nullable=True),
    sa.Column('reconciled_by', sa.String(length=255), nullable=True),
    sa.Column('debit_account', sa.String(length=100), nullable=True),
    sa.Column('credit_account', sa.String(length=100), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['related_broker_id'], ['brokers.id'], ),
    sa.ForeignKeyConstraint(['related_payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['related_policy_id'], ['policies.id'], ),
    sa.ForeignKeyConstraint(['related_premium_id'], ['premiums.id'], ),
    sa.ForeignKeyConstraint(['related_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_batch_reference'), 'transactions', ['batch_reference'], unique=False)
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_index(op.f('ix_transactions_is_reconciled'), 'transactions', ['is_reconciled'], unique=False)
    op.create_index(op.f('ix_transactions_related_broker_id'), 'transactions', ['related_broker_id'], unique=False)
    op.create_index(op.f('ix_transactions_related_payment_id'), 'transactions', ['related_payment_id'], unique=False)
    op.create_index(op.f('ix_transactions_related_policy_id'), 'transactions', ['related_policy_id'], unique=False)
    op.create_index(op.f('ix_transactions_related_premium_id'), 'transactions', ['related_premium_id'], unique=False)
    op.create_index(op.f('ix_transactions_related_user_id'), 'transactions', ['related_user_id'], unique=False)
    op.create_index(op.f('ix_transactions_status'), 'transactions', ['status'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_date'), 'transactions', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_reference'), 'transactions', ['transaction_reference'], unique=True)
    op.create_index(op.f('ix_transactions_transaction_type'), 'transactions', ['transaction_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_transaction_type'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_transaction_reference'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_transaction_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_status'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_related_user_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_related_premium_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_related_policy_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_related_payment_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_related_broker_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_is_reconciled'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_batch_reference'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_payments_transaction_reference'), table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_premium_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_date'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_premiums_premium_reference'), table_name='premiums')
    op.drop_index(op.f('ix_premiums_policy_id'), table_name='premiums')
    op.drop_index(op.f('ix_premiums_payment_status'), table_name='premiums')
    op.drop_index(op.f('ix_premiums_id'), table_name='premiums')
    op.drop_index(op.f('ix_premiums_due_date'), table_name='premiums')
    op.drop_table('premiums')
    op.drop_index(op.f('ix_policies_user_id'), table_name='policies')
    op.drop_index(op.f('ix_policies_policy_number'), table_name='policies')
    op.drop_index(op.f('ix_policies_id'), table_name='policies')
    op.drop_index(op.f('ix_policies_company_id'), table_name='policies')
    op.drop_index(op.f('ix_policies_broker_id'), table_name='policies')
    op.drop_table('policies')
    op.drop_index(op.f('ix_brokers_name'), table_name='brokers')
    op.drop_index(op.f('ix_brokers_license_number'), table_name='brokers')
    op.drop_index(op.f('ix_brokers_id'), table_name='brokers')
    op.drop_index(op.f('ix_brokers_company_id'), table_name='brokers')
    op.drop_table('brokers')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_insurance_companies_registration_number'), table_name='insurance_companies')
    op.drop_index(op.f('ix_insurance_companies_name'), table_name='insurance_companies')
    op.drop_index(op.f('ix_insurance_companies_id'), table_name='insurance_companies')
    op.drop_table('insurance_companies')
    # ### end Alembic commands ###
